baseurl = "http://thomasruble.com/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Thomas Ruble"
title = "The Fool"
disqusshortname = "ruble"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
latestpostcount = 5
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Mostly web"
copyright = "Copyright © 2018 Thomas Ruble"
#copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/foologo.png"
faviconfile = "img/logo.png"
highlightjs = true
extracssfiles = [ "/css/solarized-light.css", "/css/style.css" ]       # In your `static` directory, add/remove files as necessary.
progressively = true
lang = "en"
github = "the-fool"
email = "tr@thomasruble.com"
linkedin = "thomas-ruble-307b65106"
social_banner = "img/banner.png"
highlightjslanguages = ["elm", "typescript"]
